# A bug in Google Cloud Spanner PGEmulator

This reports one or more bugs in Google Cloud Spanner PGEmulator Dockerfile.

## Expected behaviour (with real Postgres instance)

Run command to fire up postgres Docker container:

`npm run start:postgres`

Run command to check that the database accepts connections and can analyze schema:

`APP_ENV=pgsql npm run work:step:1`

Expected result:

```
> symfony-spanner-test@1.0.0 work:step:1
> bin/console doctrine:schema:update --dump-sql

CREATE TABLE symfony_demo_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, full_name VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, PRIMARY KEY(id));
CREATE UNIQUE INDEX UNIQ_8FB094A1F85E0677 ON symfony_demo_user (username);
CREATE UNIQUE INDEX UNIQ_8FB094A1E7927C74 ON symfony_demo_user (email);
CREATE TABLE symfony_demo_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, post_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_53AD8F834B89032C ON symfony_demo_comment (post_id);
CREATE INDEX IDX_53AD8F83F675F31B ON symfony_demo_comment (author_id);
CREATE TABLE symfony_demo_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE UNIQUE INDEX UNIQ_4D5855405E237E06 ON symfony_demo_tag (name);
CREATE TABLE symfony_demo_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, summary VARCHAR(255) NOT NULL, content TEXT NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id INT NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_58A92E65F675F31B ON symfony_demo_post (author_id);
CREATE TABLE symfony_demo_post_tag (post_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY(post_id, tag_id));
CREATE INDEX IDX_6ABC1CC44B89032C ON symfony_demo_post_tag (post_id);
CREATE INDEX IDX_6ABC1CC4BAD26311 ON symfony_demo_post_tag (tag_id);
ALTER TABLE symfony_demo_comment ADD CONSTRAINT FK_53AD8F834B89032C FOREIGN KEY (post_id) REFERENCES symfony_demo_post (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE symfony_demo_comment ADD CONSTRAINT FK_53AD8F83F675F31B FOREIGN KEY (author_id) REFERENCES symfony_demo_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE symfony_demo_post ADD CONSTRAINT FK_58A92E65F675F31B FOREIGN KEY (author_id) REFERENCES symfony_demo_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE symfony_demo_post_tag ADD CONSTRAINT FK_6ABC1CC44B89032C FOREIGN KEY (post_id) REFERENCES symfony_demo_post (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE symfony_demo_post_tag ADD CONSTRAINT FK_6ABC1CC4BAD26311 FOREIGN KEY (tag_id) REFERENCES symfony_demo_tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
```

Run command to initialize database schema on the database:

`APP_ENV=pgsql npm run work:step:2`

Expected result:

`[OK] Database schema updated successfully!`

Run command to start the application in dev environment:

`APP_ENV=pgsql npm run work:step:3`

Expected result: the application is available on http://localhost:8000

## The problem wiht PGAdapter and Spanner Emulator

Invoking the above commands with spanner emulator instead:

`npm run start:emulator`

Will fire up the emulator. Then repeat the above steps but with the spanner emulator config instead of the postgres config:

`APP_ENV=emulator npm run work:step:1`

`APP_ENV=emulator npm run work:step:2`

`APP_ENV=emulator npm run work:step:3`

We can se that at steps 1 and 2 a flood of errors fills the terminal because something went wrong. Now run the following command to have a dump of the error in a single file:

`npm run fail 2>&1 >err.log`

(I don't understand why I have to redirect the output to a file twice)

The error log can now be vewed [here](err.log).